apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.containerPort }}
