apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: {{ .Values.postgres.containerPort }}
